[workspace]
members = [
  "rslint_syntax",
  "rslint_lexer",
  "rslint_parser",
  "rslint_core",
  "rslint_scope",
  "rslint_cli",
  "xtask",
]
default-members = ["rslint_cli"]

[profile]
release = { lto = true, codegen-units = 1 }
bench = { lto = true, codegen-units = 1 }
