[workspace]
members = [
  "rslint_parse",
  "rslint",
  "rslint_syntax",
  "rslint_lexer",
  "rslint_parser",
  "xtask",
]

[profile]
release = { lto = true, codegen-units = 1 }
bench = { lto = true, codegen-units = 1 }
