[package]
name = "rslint-parse"
version = "0.1.0"
authors = ["RDambrosio016 <rdambrosio016@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1.3.1"
codespan-reporting = "0.9.2"
log = "0.4.8"
rayon = "1.3.0"
ansi_term = "0.12"
fnv = "1"